### ISSUE TITLE
Should FlowCal detect incorrect package versions and raise an error?

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#100]
@nicong attempted to install `FlowCal` on a Mac, and had some issues that could have easily been detected. He initially had Python 3 installed which took me and @felixekn a while to realize. That is something that could be detected easily, raising some useful error message. I have mixed feelings here, though, cause this feels like type checking which is not the Pythonic way (would be nice if the package just happened to work in Python 3 as well...). Perhaps just a warning?

Also, apparently importing all of the submodules in `__init__.py` doesn't work in Python 3 (I replaced `__init__.py` with an empty file and was able to successfully import modules, whereas with the original `__init__.py` file we got unexplained import errors). Might be worth looking into that, because it would be nice if `FlowCal` ported to Python 3 without issue.

**Comment by castillohair** [comment]
No more discussion on this issue tagged as "question" for more than a year. Closing.

**Comment by castillohair** [comment]
Reopened as requested by @JS3xton, but I would like to close this. I think package managers (pip, setuptools too I guess) already manage dependencies well enough such that FlowCal should not do explicit version verification outside of what we already have in the `setup.py` and `requirements.txt` files.

**Comment by JS3xton** [comment]
Hmmm, ok. I think I'm OK with relying on package managers to check package versions.

There is still a kernel of this issue that I think merits attention (at least theoretically), and that is supporting Python 3. (I still agree that the ideal solution for this whole issue would have been if FlowCal would have just worked in Python 3). I think that should be raised as a separate issue, though, so I'm OK closing this one.
