### ISSUE TITLE
Smart exponentiation of channels in `excel_ui`

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#125]
The excel interface should be able to look at the amplifier type used for a sample, and exponentiate channels based on this.

This is depends on refactoring of the `FCSData.channel_info` structure.

**Comment by castillohair** [comment]
One unexpected issue is that `plot.density2d` has one global parameter for log scale, instead of separate parameters for each axis. Commit 69d242334e9d5e6f96d16e4b925a7152db6df6f0 changes this.

**Comment by castillohair** [comment]
Commit 68aa1926c40357578e6f0ce14b007894a499286c implements automatic exponentiation of the FSC/SSC channels for samples and beads.

**Comment by castillohair** [comment]
Commit 32180e7d555212b4b0bd8c5bc59e2d7ab195b804 implements automatic exponentiation of fluorescence channels if "RFI" or "a.u." are specified. However, I don't currently have files to test whether this works correctly for files with fluorescence in linear scale. All I can test is that the behavior is unchanged for our example files.

**Comment by castillohair** [comment]
One thing that remains to be done is to make the exponential transformation work with anything other than 4 logs, going from 1 to 10000. The information necessary to do this is encoded in `FCSData.amplification_type`, but currently `transform.exponentiate` is not using it. As a reminder:

> The amplification type [...] is reported as a tuple, in which the first element indicates how many decades the logarithmic amplifier covers, and the second indicates the linear value that corresponds to a channel value of zero. If the first element is zero, the amplification type is linear.

There are two ways in which I envision this working. Both assume that `transform.exponentiate` receives an additional argument, `scale`, such that the transformation is `10**(data*scale)`:
- If `scale` is not specified, `transform.exponentiate` attempts to get the scale from `data.amplification_type(channels)`. This also means that the function would not actually transform, by default, data taken with a linear amplifier. However, if one specifies any value for `scale`, the function blindly transforms the data.
- `transform.exponentiate` always blindly transforms the data given. It is up to the Excel UI to calculate the appropriate value of `scale`.

I think I like the first option more. It sounds easier to use in an interactive environment.

I'd like your opinion on this, @JS3xton.

**Comment by JS3xton** [comment]
Hmmm, guess I'm a little confused. What is the equation that relates the 2 amplifier parameters (# of decades and value of 0) to the raw channel value and the transformed RFI value? Seems like there are 2 degrees of freedom there, but you're only proposing to incorporate 1 of those into `transform.exponentiate`?

You've kind of raised a related point: should `transform.exponentiate` be responsible for taking a raw channel value and the amplifier parameters and doing whatever is necessary to get an RFI unit? Or should it ignorantly just apply an exponentiation transformation with some specified parameters. As it's currently named, I'm in favor of `transform.exponentiate` ignorantly applying some transformation (which would be well documented of course), in which case there should be no guessing of `scale` in my opinion; throw an error if it's not specified or have some default value that's documented. Reconciling the different amplifier paremeter values could be the job of another function (`transform.to_RFI()`?) or just done in the Excel UI. Having not tried this at all, it would be kind of nice to package this whole procedure into a function that other people could use outside of the Excel UI, but this may be a low-usage edge case which may not be worth doing.

**Comment by castillohair** [comment]
I think you're right, it may make more sense to use a different function to do automatic transformation to a.u.. `transform.exponentiate` should ignorantly apply its transformation, which would be consistent with other ignorant transformation functions that we might implement in the future (e.g. logicle, which mammalian people use a lot, see http://docs.flowjo.com/vx/graphs-and-gating/gw-transform-overview/). I'll figure out proper function signatures later.

**Comment by castillohair** [comment]
The relationship between channel units and arbitrary units when a logarithmic amplifier is used, according to the standard (http://isac-net.org/PDFS/90/9090600d-19be-460d-83fc-f8a8b004e0f9.pdf) is:

```
xs = f2*10^(f1 * (xc/r))
```

Where `xc` and `xs` are the fluorescence of an event in channel units and a.u., respectively; `(f1, f2)` are the two numbers in `FCSData.amplification_type`, and `r` is the ADC range in the `$PnR` keyword parameter.

**Comment by castillohair** [comment]
In summary, I propose a new transformation function, `to_rfi(data, channel, range=None, amplification_type=None)`, where `range` specifies the ADC range, equivalent from the parameter $PnR, and `amplification_type` is a tuple, similar to the parameter $PnE. If not specified, these will be read from `len(data.domain[channel])` and `data.amplification_type`, respectively. This function will be used in the Excel UI in all instances in which a transformation to au is required.

I don't know what to do now with `exponentiate`, though. The automatic scaling by 256 seems very arbitrary, and will not have any purpose now that `to_rfi` exists. I would propose to either remove this scaling, or make the scaling an optional argument. Also, we should take into account that any changes to this function will impact current users that are using the python API (e.g. Lucas).

**Comment by castillohair** [comment]
I talked to @JS3xton and we decided to eliminate `exponentiate`, as it's only purpose was to transform data to a.u., but the new proposed `to_rfi` does this better.

**Comment by castillohair** [comment]
Commit 0a840b87459b31ca4008418a836befdd884d7756 implements `to_rfi`. Changes in the Excel UI  to use this function are still remaining.

**Comment by castillohair** [comment]
48fb82a48afc7c6ae9b696c4d029956e46a78235 modifies the Excel UI to use `to_rfi`.
