### ISSUE TITLE
User-friendly errors in `excel_ui`

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#126]
TODO: list common error situations. Examples are #98 and #99.

**Comment by castillohair** [comment]
Issues #65, #184, and #130 are examples of errors that we could handle better.

I propose a couple of things here:
1. Have a new column in the samples table in the output file, "Notes" (or any other name), that will contain error messages and warnings originated from processing each sample. If processing is correct,  this field will be empty.
2. Create a new set of exceptions, derived from a new class `FlowCalException`, that will be thrown in response to the errors that we are supposed to handle gracefully at least in the Excel UI.
3. During processing of samples, all the code inside the for loop (line 453 in file excel_ui.py) should be wrapped in a `try` block. Any `FlowCalException` thrown will be caught and dealt by writing to the Notes field. A similar thing could be done for beads.

**Comment by JS3xton** [comment]
These proposals sound like good ideas to me.

**Comment by castillohair** [comment]
Solved as part of #194.
