### ISSUE TITLE
Should throw error if you try to MEF fluorescence data collected through linear amplifier (FSC,SSC amplifier shouldn't matter)

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#130]
The standard curve currently implemented in `mef.fit_standard_curve()` is crafted to assume that the x values (assumed to be channel values) are logarithmically related to the y values (known MEF values from the datasheet). This should be true if data was collected through a log amplifier.

If a linear amplifier is detected, an error should be thrown if you try to MEF (at least until an appropriate standard curve can be implemented for a linear relationship between channel values and MEF values). Not sure where this error is appropriate, `excel_ui` at least. Not sure if it should go anywhere else, though, because `mef.fit_standard_curve()` doesn't ask for the amplifier type (nor should it, IMO).

**Comment by castillohair** [comment]
I think this is overriden by #192. Is there any problem if I close this issue?

**Comment by JS3xton** [comment]
Seems like #192 should be updated to not refer to floating point if you want to close this one? This issue deals with linear amplifiers in general (independent of the $DATATYPE). Maybe we get linear amplifiers for free with #192 if FlowCal is modular enough (I haven't looked closely). I think floating point already works, so I really think #192 is a rehashing of this issue. I agree that we should handle linear amplifiers, though, not just throw an error (in that sense, this issue should be update).

**Comment by castillohair** [comment]
I can leave both open, but they will both be closed when the two files that we recently got are able to pass through the Excel UI without issues.

**Comment by castillohair** [comment]
#213 is able to convert floating-point linear data to MEF.
