### ISSUE TITLE
gate and io module namedtuple descriptions consistent?

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#143]
The `gate` module and the `io` module do not describe `namedtuple` fields consistently in their function/class docstrings. In `gate`, I tried to apply a recursive docstring approach (where I indented and then described the `namedtuple` fields as I would other Parameters or Returns). In `io`, we simply list the contents in a bulleted list. Not sure what to do here, because I actually think they both look fine in their respective contexts. We could just *not* force them to report `namedtuple` fields in the same way (i.e. leave it like it is).

One small thing I would change either way is in `gate` module, remove the 2nd reference to `namedtuple` in the description right after describing that the return value is a `namedtuple` (same thing we did in `io`).

Related to #139.

**Comment by castillohair** [comment]
Yeah I don't think these are comparable. The namedtuple in `io` is only one of the arguments in all the functions except for one, whereas in `gate` we're using the namedtuple as a replacement for the default tuple output. I'm ok with leaving this as it is.

Note that all documentation comments should be made towards the `docs` branch for now.
