### ISSUE TITLE
Make package documentation consistent with paper

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#166]
- GitHub repository description: "Python Flow Cytometry Library" -> "Python Flow Cytometry **Calibration** Library"
- Mention "calibration" in README. Ideally something more concrete from the paper, e.g. "Calibrate from a.u. to MEF units"

**Comment by castillohair** [comment]
Currently in `master`.

**Comment by castillohair** [comment]
Reopened because the repo description is different from the README and everything else INSIDE the repo.

**Comment by castillohair** [comment]
I'm actually not sure about point 1. I think I don't want to restrict the package description to calibration only. On the other hand, the name is already `FlowCal`, so we might as well. More thoughts on this?

**Comment by JS3xton** [comment]
I originally felt the same way (hence the ambiguous `fc` which was originally supposed to stand for "flow cytometry", a general Python package for all flow cytometry needs). I think the package has become quite focused on calibration now, though (it's in the name, as you've pointed out). More important to me, though, is that we be consistent, and we made extensive use of "calibration" in the paper.

**Comment by castillohair** [comment]
Done.
