### ISSUE TITLE
Python API tutorials

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#167]
- Determining channel names (either via `FCSData` or `FCSFile`)
- Full analysis examples
  - 1 version from scratch? (no Excel-UI, no pandas?), probably simpler
  - 1 version which employs most of Excel UI and drops down to Python just before the last step of Excel UI (writing new XLSX sheet and printing histograms; probably requires pandas).
  - Changing the standard curve (e.g. no bead autofluorescence which would possibly be appropriate for our FL3)
  - Extracting standard curve parameters (if that isn't exposed in the output XLSX sheet yet)
  - Changing the subpopulation representative statistic (e.g. to mean, as suggested by some other sources)
  - Modifying peak selection (either changing parameters or turning it off entirely)
  - Change clustering algorithm? (can't really think of a much better alternative, though; I'm pretty happy with GMM when it works)

Not sure what gh-pages supports; should these be Jupyter notebooks? Or more like Examples from docstrings?

**Comment by JS3xton** [comment]
- How to get a SVG file of a plot.

**Comment by castillohair** [comment]
I think I want to keep it a little more basic. I was thinking about something like
- Open a file, slicing an FCSData, accessing the events.
- Simple workflow: open, exp-transform, density gate, plot
- Obtain a standard curve: call get_transform_fxn, explaining all the parts that can be customized. Use the transform function to convert data to MEF.
- Processing an input excel file from python, and getting all the FCSData objects.

Yeah it would be nice if these were actual ipython notebooks that could operate on the files in the examples folder. I'll look into how to do this.
