### ISSUE TITLE
FlowCal version in output XLSX file?

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#168]
Might be kinda nice if FlowCal automatically put its version number in the output XLSX sheet somewhere. Not sure where the best place would be, though.

**Comment by castillohair** [comment]
Sounds like a good idea. Some alternatives for where to put this would be:
- In the output file name (`experiment_output_1_0_0b1.xlsx`)
- In a completely new sheet (names could be "About" or "About FlowCal" or "Info").

**Comment by JS3xton** [comment]
I vote for new sheet. I don't like mangling file names any further than they already are with "_output". If you were trying to further automate anything based on that filename, you'd now have to know the FlowCal version number. I like mentioning "FlowCal" in the sheet name, though, to differentiate it from a sheet more specific to the experiment (I've added on an "Experimental Setup" sheet, etc. to some of my output sheets; "Info" or "About" could easily be interpreted as referring to the experiment).

**Comment by castillohair** [comment]
Commit 4fb74cd3ba5eda4c3276de86b4d64a9b673a5e72 gives a shot to this idea. In summary, a new sheet called "About FlowCal" has been defined, in which a table with columns "keyword" and "values" have been defined. Each keyword:value pair would correspond to some bit of information about how FlowCal has been run. For now, the only piece of information is the FlowCal version, but one could imagine adding the required module versions, the python version, the OS, date, whether the "verbose" and "plot" flags were used, etc.

If there is any other piece of information that you think should go here, let me know. Otherwise, I'll merge into develop and let people raise new issues if they think something else should go here.

**Comment by JS3xton** [comment]
- I like date (and maybe time?). More specifically, maybe "Analysis Date" or "Date of Analysis".
- Not sure what you mean by required module versions, but I assume you mean the actual version used, right? not just regurgitating the README. That sounds mildly useful. I would include OS too, if you were going to add this in. This only really sounds useful for debugging, though; (hopefully) not a common use case.
- I don't really think I'd care about the "verbose" or "plot" flags to be honest.
- Maybe name of the input file? Since it looks like we'll support specifying your own input file in #179.

**Comment by JS3xton** [comment]
- (trying to think about what else I see in About tabs for other software) could also put a pointer to whatever FlowCal landing page we settle on (http://taborlab.github.io/FlowCal/ ?)

**Comment by castillohair** [comment]
On second thought, some of these may be not-so-trivial to implement:
- module versions: The list of modules would have to be hardcoded, which I don't like.
- OS name: would require a non-trivial amount of testing to make sure we're getting this right, and some thought on how much detail to include (compilation number? linux distro name?).
  - Actually, I think it would be more useful to have the python version, and whether it's coming from anaconda or from another source. Again, sounds like it would require some non-trivial amount of research and testing.
- URL sounds like a good idea. However, we either hardcode it, or save it in `__init__.py`, such that we get `FlowCal.__url__`. `setup.py` would also need to pull the url from this source. But I haven't seen if this is the recommended way of including urls, or if there is a better one. Again, I think doing it well is outside the scope of this issue.

I'm going to add analysis date and time, and input file name. If there is enough demand for the others, we can discuss them in another issue.

**Comment by castillohair** [comment]
Date and time added in 0e39c72a374f9e7b0241428cdc6308aa2d7bd031

**Comment by castillohair** [comment]
Input file name added in 7787b54c06a7bc4b05a3820cfe4b17f4a5c71698

**Comment by castillohair** [comment]
In 5aa77fdd7b438f64d1a86c5b1d1b5f7bb1707ff5, I changed the name of "About FlowCal" sheet to "About Analysis", since all of the new things added are not really properties of the FlowCal package.
