### ISSUE TITLE
Add the channel gains of beads to the output excel file within the beads tab

### ISSUE THREAD

**Issue by felixekn** [taborlab/FlowCal#175]
Quickly identifying the gain of bead files allows the user to double check that the beads were measured at the gains which the samples were measured at. This feature in past versions of FC has been very helpful in diagnosing data irregularities.

**Comment by castillohair** [comment]
Commit a77a8c6da7dc0ef047b13fd5cdefdd318932dba1 implements this. In addition to printing the detector voltage (gain) to the beads sheet, the program now also prints the acquisition time and the number of (gated) events. Running it against the example files gives the correct results as far as I can tell.

@felixekn please test it if you can. @taborlab/flowcal-developers, if there is no proposed change or complain within the next 24 hours, I'll merge into develop.

I think #38 would not be hard to implement after this.
