### ISSUE TITLE
viridis as default colormap for density plots?

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#181]
The colormaps here: https://bids.github.io/colormap/ seem well thought out. Looks like they already exist in matplotlib 1.5 and will be the default in matplotlib 2.0, so using them might eliminate a dependency on `palettable`.

Looks like we're currently using `palettable.colorbrewer.diverging.Spectral_8_r.mpl_colormap`, which may achieve the same things that the ones above do, I don't know. I'm also not sure how complicated it is to support the colormaps mentioned above during this transition period. May be better to wait until they're the matplotlib default, and then update FlowCal to embrace them?

**Comment by castillohair** [comment]
I think the first step would be to generate a density plot and a couple of clustering plots, to see if we like the result and we want to go further with this. I personally really like the current clustering plots. The different colors indicate different discrete groups, but there is also an order associated with them. So I wouldn't care about perceptual uniformity here. But I can see the benefit of changing the 2D density plots.

There is also the issue of the standard curve plots, which would revert to the plain blue, red, and green used by `matplotlib` by default. This means that we would still need `palettable` for this plot. They are changing the default styles in `matplotlib 2.0` (http://matplotlib.org/style_changes.html), but I can't find specifics. You might wanna spend some time in the github repo (https://github.com/matplotlib/matplotlib) and see if you can find something. I'd like to have this information and see a sample plot before proceeding any further.

**Comment by castillohair** [comment]
On the standard curve plots, it turns out matplotlib includes styles besides the classic one. This includes some styles from `seaborn` and `ggplot`. Some of the `seaborn` styles are similar to what is currently done for the standard curves. See http://matplotlib.org/users/style_sheets.html.

**Comment by castillohair** [comment]
Now that some time has passed and I have some experience with viridis, I have to say that I'm warming up to this idea. Defaults in matplotlib > 2.0.0 are pretty nice and could justify ditching palettable. If anyone wants to do this, I'd be interested. I probably won't do it, though.
