### ISSUE TITLE
add "histograms" flag to FlowCal command line to control production of Histograms sheet.

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#182]
Creation of the Histograms tab takes a noticeable amount of time, and I often don't care about that tab (especially when I'm iteratively tweaking gate fractions and inclusion of known bead subpopulation values). A command line flag to specify whether the Histograms tab should be created (e.g. `FlowCal -h`, `FlowCal --histograms`, `FlowCal --histograms_tab`, `FlowCal --histograms_sheet`) seems like a simple enhancement to grant me control over that sheet. (Or the converse flag if you want to keep the default behavior as producing the sheet, whatever makes sense).

**Comment by castillohair** [comment]
Could this be generalized to other types of outputs? bead statistics, sample statistics, "about" sheet, etc?

**Comment by castillohair** [comment]
Solution merged into develop, see #242.
