### ISSUE TITLE
Robust handling of bad samples

### ISSUE THREAD

**Issue by thoreusc** [taborlab/FlowCal#184]
Right now, FlowCal does not handle bad sample data very well. During batch-processing, the whole process will crash if a bad sample is processed, and the analysis of all of the preceding samples is lost.

I know that this falls into the realm of "stupid user errors" and is not a problem of FlowCal directly. However, it would be much appreciated if un-processable samples were just skipped, or if the analysis results of that sample were just filled with some null values.

I've attached a bad sample for reference.
[Cells187.zip](https://github.com/taborlab/FlowCal/files/151869/Cells187.zip)

**Comment by castillohair** [comment]
Related to #126.

**Comment by castillohair** [comment]
Solved as part of #194.
