### ISSUE TITLE
Normalized histograms in log scale do not work properly

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#186]
Running the following code in the examples folder:

``` python
#!/usr/bin/python
import numpy
import scipy
import matplotlib
from matplotlib import pyplot
import palettable

import FlowCal
import smc_utils

# Excel file name
input_filename = 'experiment.xlsx'

verbose = True
plot_samples = False

if __name__ == "__main__":

    # Read relevant tables from workbook
    instruments_table = FlowCal.excel_ui.read_table(input_filename,
                                                    sheetname='Instruments',
                                                    index_col='ID')
    beads_table = FlowCal.excel_ui.read_table(input_filename,
                                              sheetname='Beads',
                                              index_col='ID')
    samples_table = FlowCal.excel_ui.read_table(input_filename,
                                                sheetname='Samples',
                                                index_col='ID')

    # Process beads samples
    beads_samples, mef_transform_fxns = FlowCal.excel_ui.process_beads_table(
        beads_table,
        instruments_table,
        verbose=verbose,
        plot=plot_samples,
        plot_dir='plot_beads')

    # Process samples
    samples = FlowCal.excel_ui.process_samples_table(
        samples_table,
        instruments_table,
        mef_transform_fxns=mef_transform_fxns,
        verbose=verbose,
        plot=plot_samples,
        plot_dir='plot_samples')

    # Plot histograms
    FlowCal.plot.hist1d([samples[3], samples[4]],
                        channel='FL1-H',
                        log=True,
                        savefig='hist.png')

    FlowCal.plot.hist1d([samples[3], samples[4]],
                        channel='FL1-H',
                        normed=True,
                        log=True,
                        savefig='hist_normed.png')
```

...produces two plots: one histogram of gated samples 4 and 5 in log scale:
![hist](https://cloud.githubusercontent.com/assets/1529481/13592315/bc3b1b1a-e4b6-11e5-9beb-b599ce3b00b1.png)

and one histogram with a normalized y axis:
![hist_normed](https://cloud.githubusercontent.com/assets/1529481/13592324/c53d4dfa-e4b6-11e5-9303-954cd255318f.png)

The latter should be identical to the former, but with the y axis rescaled, although differently in both samples. However, the shape of the histogram is changed when plotting the normalized version.

**Comment by castillohair** [comment]
Upon closer inspection, normalization with `normed` is performed such that the area under the curve is one (http://matplotlib.org/api/pyplot_api.html). Therefore, thinner bins are scaled up, which results in bins to the left of the plot being higher in the normalized version. Overall, this method would give a different histogram shape in channel units compared to a.u. or MEF. Perhaps surprisingly, this is correct if what you're trying to plot is a probability density function, and `FlowCal.plot.hist`'s documentation is clear on this. So this is not actually a bug.

However, I think an option for a probability mass function would be a nice addition. Here, the sum of all bins' height would be equal to one. This would preserve the shape of the histogram independently of whether data is in channel units or a.u./MEF.

Therefore, I think the argument "normed" should be dropped, due to not being specific enough, and the following two arguments should be available:
- `normed_pdf` or `normed_area`, which would result in identical behavior as `normed` currently has.
- `normed_pmf` or `normed_height`, which would normalize heights, as described above.

**Comment by castillohair** [comment]
For an equivalent example as in the previous example code, the following results from a preeliminary implementation of a pmf:

![hist_normed](https://cloud.githubusercontent.com/assets/1529481/13609900/99a88b5e-e520-11e5-897c-ed61bfc83dd1.png)

**Comment by JS3xton** [comment]
I was gonna say, your original "normalized" plot looks reminiscent of my old MATLAB plots where I tried to calculate the PDF correctly. Indeed, it made the thinner leftmost bins taller in order to preserve the integral. You can also see what I think I figured out as a 1/x relationship in the bin heights for bins near 0 that originated from a bin with the same number of counts. I actually implemented a "rebin" option which calculated the CDF and then rebinned the CDF to generate a "more normal" looking histogram. It kinda helped, but still had some anomalies near 0.

I like the idea of `norm_pdf` vs. `norm_pmf`, but I don't know how to differentiate them visually. Right now, you have two plots which look very different, but you are claiming both represent the same thing. A PMF with lollipops versus a filled area plot would distinguish PMF from PDF, but as we've discussed previously, the lollipop plot for a PMF doesn't look very good (especially one as dense as this one would be).

**Comment by castillohair** [comment]
> I like the idea of norm_pdf vs. norm_pmf, but I don't know how to differentiate them visually.

The function `hist` is tied to a specific representation, which is a histogram. I think that `norm_pdf` and `norm_pmf` change the histogram's scaling, but it should still be a histogram. Whether it means a pdf or pmf is up to the user, which is why these options should be available.

Alternatively, the y axis label could be changed to "Counts (normalized)" in the case of a pmf, and/or the y axis range could be changed to 0-100%.

**Comment by JS3xton** [comment]
Yeah, I can't think of a good alternative to the traditional histogram (what I previously called a "filled area plot") for the PMF. I'm in favor of "Counts (normalized)" for the PMF and "Probability" for the PDF as y-axis labels to differentiate the two, though. This is pretty minor, though.

**Comment by castillohair** [comment]
Commit 6c9e1d68a1bef1d813e64d6133f15d4f501c0d32 solves this issue.
