### ISSUE TITLE
$DATE reading

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#187]
We now have access to a file in which the $DATE keyword is stored as `2016-Mar-03`, which is different from the assumed format `%d-%b-%Y`. Therefore, loading the file with `FCSData` fails.

**Comment by castillohair** [comment]
Note that `%Y-%b-%d` is not the standard format specified in the FCS standard, so in principle we wouldn't need to cover it. However, I think it is a failure of FCSData to crash in response to a nonstandard field. If the data field cannot be read, it should be set to None.

**Comment by JS3xton** [comment]
agree

**Comment by castillohair** [comment]
a1d44e03024eaa32b036170eeaa1b7314d3ae979 handles the new date format, and returns `None` if the date cannot be parsed. It also fixes a different bug with the `CREATOR` keyword found when loading the same file.
