### ISSUE TITLE
Kernel dies when gating or plotting density maps, single .fcs file

### ISSUE THREAD

**Issue by jason-ship-it** [taborlab/FlowCal#205]
I'm reading an .fcs file, converting to rfi and then trying to gate. Kernel dies after 4-5 minutes, same when trying to plot density maps. Histogram plotting works.
Is there something wrong on my end?

Here's the file I'm using and the code.
[fcs-file.zip](https://github.com/taborlab/FlowCal/files/251221/fcs-file.zip)

```
import FlowCal
import matplotlib.pyplot as put
import glob
import numpy as np

fcs_read = []
for i in glob.glob("*.fcs") :
    fcs_read.append(FlowCal.io.FCSData(i))

data_au = []
for j in fcs_read:
    data_au.append(FlowCal.transform.to_rfi(j, channels=['FSC-A', 'FSC-H', 'SSC-A', 'SSC-H', 'B1-A']))

percent = 0.5
data_au_gated = []
data_au_gated.append(FlowCal.gate.density2d( data_au[0], channels=['FSC-A', 'SSC-A'], gate_fraction=percent))
```

**Comment by castillohair** [comment]
This seems to be related to #192. In short, each channel in your fcs file has a resolution of 262143 (18 bits). Any 2D function (`gate.density2d()` and `plot.density2d()`) will try, by default, to generate 262143^2 bins, which will result in a memory error. We discovered this issue not so long ago, and we're working on a fix that we will push in the next couple of days.

In the meantime, manually specifying the bins should work for you. The following code works for me with your file:

``` python
import FlowCal
from matplotlib import pyplot as plt
import numpy as np

d = FlowCal.io.FCSData('Jf2016-05-04.0001.fcs')
d = FlowCal.transform.to_rfi(
    d,
    channels=['FSC-A', 'FSC-H', 'SSC-A', 'SSC-H', 'B1-A'])

# Density gate
percent = 0.5
dg = FlowCal.gate.density2d(
    d,
    channels=['FSC-A', 'SSC-A'],
    gate_fraction=percent,
    bins=[np.logspace(0, 5.42, 1024),
          np.logspace(0, 5.42, 1024)])

# Plot ungated data
FlowCal.plot.density2d(d,
                       channels=['FSC-A', 'SSC-A'],
                       mode='scatter',
                       bins=[np.logspace(0, 5.42, 1024),
                             np.logspace(0, 5.42, 1024)],
                       xlog=True,
                       ylog=True,
                       savefig='ungated.png')

# Plot gated data
FlowCal.plot.density2d(dg,
                       channels=['FSC-A', 'SSC-A'],
                       mode='scatter',
                       bins=[np.logspace(0, 5.42, 1024),
                             np.logspace(0, 5.42, 1024)],
                       xlog=True,
                       ylog=True,
                       savefig='gated.png')
```

ungated.png
![ungated](https://cloud.githubusercontent.com/assets/1529481/15059286/3b912b76-12e7-11e6-8271-c9e3a4035848.png)

gated.png
![gated](https://cloud.githubusercontent.com/assets/1529481/15059287/3f44ff4a-12e7-11e6-9872-d0c8433e150e.png)

With the fix that we're about to push, you wouldn't need to specify `bins` and still get a good default that wouldn't crash your computer. We'll let you know when we finish this.

**Comment by jason-ship-it** [comment]
Thank you, it works now on my end too!

**Comment by castillohair** [comment]
Just to update on this, the new version 1.1.0 has been released. This should handle your file more easily than the previous version.

The following script should generate a plot from your file and FlowCal 1.1.0:

``` python
import FlowCal
from matplotlib import pyplot as plt
import numpy as np

# Load file
d = FlowCal.io.FCSData('Jf2016-05-04.0001.fcs')

# Define channels
sc_channels = ['FSC-A', 'SSC-A']
fl_channels = ['B1-A']

# Transform to a.u.
d = FlowCal.transform.to_rfi(d)

# Attempt density gating
dg, __, dc = FlowCal.gate.density2d(
    d,
    channels=sc_channels,
    gate_fraction=0.30,
    sigma=20,
    full_output=True)

# Plot
FlowCal.plot.density_and_hist(
    d,
    gated_data=dg,
    gate_contour=dc,
    density_channels=sc_channels,
    density_params={'mode': 'scatter', 'sigma': 20},
    hist_channels=fl_channels,
    savefig='density_hist.png')
```

If you prefer the Excel UI, attached is an input file that should work with your file.

[experiment.xlsx](https://github.com/taborlab/FlowCal/files/332799/experiment.xlsx)

Let me know if this works for you. Thanks.
