### ISSUE TITLE
DATA size does not match expected array size

### ISSUE THREAD

**Issue by agtebo** [taborlab/FlowCal#212]
I wanted to try out your software on my data, but I'm unable to load my files. The data was acquired on an Accuri c6 flow cytometer and are exported to FCS 3.0 format. Attempting to load my data using results in output: 
`ValueError: DATA size does not match expected array size (array size = 2800000 bytes, DATA segment size = 2800001 bytes)`

I'm pretty new to flow cytometry and I'm unsure how to troubleshoot this. Running OSX 10.11.4 and python 2.7.11 with Anaconda 4.0.0. I'm happy to share an example of my .fcs file if that would helpful. 

Thank you!

**Comment by castillohair** [comment]
Hi,

We are working on an update to significantly improve compatibility (see #203). It should be coming out in the next couple of days. It would definitely be useful if you sent us your file for testing before we release the new version.

Thanks.

**Comment by agtebo** [comment]
Cool! I apologize for submitting a duplicate issue, then. You can find an example .fcs from our instrument (Accuri c6) [here](https://app.box.com/s/g92de47hvqjlxbxuma49o2sdetd59g7f). This sample is bacteria expressing a fluorescent protein, nothing too fancy. Hope this helps.

**Comment by castillohair** [comment]
Just wanted to give an update on this. The new version 1.1.0 has been released, which should be able to handle your file.

If you prefer writing code, the following script should read your file and produce a plot from it:

``` python
import FlowCal
from matplotlib import pyplot as plt
import numpy as np

# Load file
d = FlowCal.io.FCSData('A02 YFAST HMBR.fcs')

# Define channels
sc_channels = ['FSC-A', 'SSC-A']
fl_channels = ['FL1-A', 'FL2-A', 'FL3-A', 'FL4-A']

# Transform to a.u.
d = FlowCal.transform.to_rfi(d)

# Perform low-high gating
dg = FlowCal.gate.high_low(d, channels=sc_channels + fl_channels)

# Attempt density gating
dg, __, dc = FlowCal.gate.density2d(
    dg,
    channels=sc_channels,
    gate_fraction=0.75,
    full_output=True)

# Plot
FlowCal.plot.density_and_hist(
    d,
    gated_data=dg,
    gate_contour=dc,
    density_channels=sc_channels,
    density_params={'mode': 'scatter'},
    hist_channels=fl_channels,
    savefig='density_hist.png')
```

If you prefer using the Excel UI, I'm attaching an Excel file that should work with your file.

[experiment.xlsx](https://github.com/taborlab/FlowCal/files/332796/experiment.xlsx)

Let me know if this works for you. Thanks.
