### ISSUE TITLE
Data reading overflow

### ISSUE THREAD

**Issue by hansyulian** [taborlab/FlowCal#216]
When reading data from one .fcs file, if the data already exceed the maximum value, example the data value is 20,000,000 while the minimum value is 0 and maximum value defined is 16,777,215, the data value have overflow issue where the value got reset from 0 again for the rest of 20,000,000 - 16,777,215 = 3,222,785. so instead of giving value of 20,000,000 or 16,777,215, it giving 3,222,785 instead. which is definitely wrong value.

**Comment by JS3xton** [comment]
It would help to know what the `$DATATYPE` of your file is (e.g. integer or floating point), and possibly what version of FlowCal you're using. Can you upload an example file so we can look at it? Thanks.

**Comment by hansyulian** [comment]
The $DATATYPE is integer. the version of flowcal is 1.1.0

Here attached the sample fcs file. and the one with likely overflow is row number 18248 if you counting start from 0. Attached the image here is the row with FSC-A value 16777215 which is actually exceed 16777215, but in BD Accuri, the exported .csv file already replace the exceeded value with maximum value.

Thank you.

[Sample A01.zip](https://github.com/taborlab/FlowCal/files/399176/Sample.A01.zip)
![capture](https://cloud.githubusercontent.com/assets/10959546/17362652/a4f00dfa-59a8-11e6-9031-793f860dab60.PNG)

**Comment by castillohair** [comment]
Hello Hans,

Sorry for the delay, it's been a busy week.

Unfortunately, the problem here is that your file is not adhering to the standard. For your file (`$DATATYPE == 'I'`) the maximum parameter value is 16777215, no exceptions. It seems that your acquisition software is storing information incorrectly when trying to save values greater than 16777215; therefore there is no way of interpreting your data correctly and follow the standard at the same time. I recommend you to switch to floating-point data if possible (`$DATATYPE == 'F'`), since the standard is a little more flexible in this case.

More technically, for `$DATATYPE == 'I'` the value specified in `$PnR` (in your case 16777216) is the maximum parameter value allowed. This is different from `$PnB`, which specifies the number of bits used (in your case, 32). To store 16777216 values you only need 24 bits. The standard says that with `$PnR ==16777216` and `$PnB == 32` only the first 24 bits should be taken into account, and the other 8 bits should be ignored. That is exactly what FlowCal does. But it seems that your software is using those other 8 bits to store values greater than 16777216. This is why we get different numbers.

For more reference, please check http://isac-net.org/PDFS/90/9090600d-19be-460d-83fc-f8a8b004e0f9.pdf, especially the discussions on `$PnB` and `$PnR`.

Let us know if you have any other questions.

**Comment by JS3xton** [comment]
Just to follow up on what @castillohair said, I see 2 possibilities with your situation.

First, to establish some common ground about your file (restating much of what @castillohair said above):
- `$DATATYPE == 'I'` tells us that the acquisition software wrote data as unsigned integers
- `$PnB == 32` (for all channels) tells us that the acquisition software used 32 bits (4 bytes) to store each data point (for each of the `$PAR == 14` channels)
- `$PnR == 16777216` (for all channels) tells us the "maximum range" for any data point (as @castillohair mentioned, check out the [FCS standards](http://isac-net.org/PDFS/90/9090600d-19be-460d-83fc-f8a8b004e0f9.pdf) for more details on the `$PnR` keyword and what it specifies)
  - It follows that you should only ever need ceil(log2(`$PnR`)) = 24 bits (3 bytes) to store values ranging from 0 to the 16777215 (which, in this case, is less than the number of bits specified in `$PnB`).
  - The FCS standards permit the acquisition software to store extra information in any unused bits (e.g. the most significant byte of your 32-bit data points), and calls upon analysis software to mask off any unused bits (determined by comparing `$PnB` and `$PnR`) before interpreting the data stored in the DATA segment of a .fcs file (which is what FlowCal does by default).

Now, this leaves us with 2 possibilities, as I see it:
1. Your acquisition software is _legitimately_ storing additional information in the most significant byte of your data points (as permitted by the FCS standards), in which case FlowCal is _correctly_ masking that information off before interpreting that data point
2. Your acquisition software is _illegitimately_ using more than 24 bits to describe your data points with values exceeding the maximum range as specified by the `$PnR` keywords (in violation of the FCS standards)

@castillohair and I looked at the raw data for your file and concluded that the 2nd scenario was more likely for the following reasons:
- the most significant byte was frequently zero (if the acquisition software was systematically storing additional information in that most significant byte, I would expect most of the data points to have nonzero values for that most significant byte)
- only the least significant bit of the most significant byte was used (that we saw), consistent with the hypothesis that the acquisition software was simply overflowing the 24 bits permitted into that 25th bit

FlowCal currently adheres to a subset of the FCS standards, and thus may not support off-standard files by default. That being said, the machinery does exist under the hood (i.e. via the Python API) to manually import .fcs files _without_ masking off unused bits. Specifically, if you invoke `FlowCal.io.read_fcs_data_segment()` with `param_ranges=None`, you should get a numpy array representing the DATA segment of the .fcs file _without_ any bit masking. FlowCal version 1.1.0 invokes this function [here](https://github.com/taborlab/FlowCal/blob/ca52afae6594313dbcd82ce99bf4ca757cb0ea69/FlowCal/io.py#L713) (requires that you manually import the HEADER and TEXT segments of the .fcs file using the corresponding `FlowCal.io` module function calls). The vanilla numpy array may not be as easy to use as the `FlowCal.io.FCSData` class, but it might work for you in a pinch.

**Comment by hansyulian** [comment]
After reviewing this, i remember that for integers, there are only 1,2,4, and 8 bytes. in this case, 16777215 is the maximum value for unsigned 3-bytes integer, which is either we will really save it in form of 3 bytes from the code, occupy ?? ?? ?? or since we most likely will store it in standard variable which is at least must be 4 bytes and occupy ?? ?? ?? ??. In this case it seems the standard will save it into 4 bytes instead of 3 bytes and FlowCal only read the first 3 bytes, skip the 4th one and go to read next data.

This behavior is not completely wrong as long as you follow the standard, but in my opinion, vendors have their own will, either they will make the exceed values  into 16777215 or just let it stored as it is, all of these up to vendors and they may have difference for each vendor.

To me, i prefer if this one can be either these way:
1. Read all 4 bytes, convert it into 4 bytes integer, let the value be like that, and let developer decide what they want to do with the excess values.
2. Read all the 4 bytes, if you detect it excess, turn it into the maximum value

and of course, these behavior are configurable, let the developers decide it. rather than only read the 3 bytes. Is there any drawback reading 3 bytes instead of 4? if the value like FF 00 00 00 will still giving us result 256 when reading 3 bytes, the same thing will give us the same value in 4 bytes, but in case FF 00 00 FF, 4 bytes have their advantage here.

**Comment by JS3xton** [comment]
The drawback is that FlowCal cannot tell the difference between:

(1) acquisition software _legitimately_ storing additional information in the unused bits of a data point (as permitted by the FCS standards), which should be masked off before interpreting the data point

and

(2) acquisition software _illegitimately_ using more than ceil(log2(`$PnR`)) bits (when `$DATATYPE == 'I'`) to describe a data point (in violation of the FCS standards)

Both scenarios look the same from FlowCal's perspective (it's hard to "detect excess", as you put it), but one situation requires bit masking and the other situation does not. So, for example, if FlowCal just read in all 4 bytes from a file that was written according to (1), then FlowCal would _incorrectly_ report a value larger than the maximum range as defined by `$PnR`, when it should have instead masked off the most significant byte. Given our inability to easily differentiate between case (1) and case (2), we prefer to support files that follow the FCS standards. As mentioned previously, though, you, as the developer, can indeed override this behavior and import data without bit masking (see end of previous comment).

**Comment by hansyulian** [comment]
no need to make it able to detect, you can just put a default behavior for FlowCal, but still let user able to select which behavior they want it to be when reading the data. I think this one will work better, and yet another feature that FlowCal will have.
