### ISSUE TITLE
Excel UI should plot to standard plot output (e.g. Jupyter notebook) if no plot directory is specified

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#218]
`FlowCal.excel_ui.process_beads_table()` and `FlowCal.excel_ui.process_samples_table` should allow for `plot_dir` to be `None` (or `False`?), in which case they should render their plots to the console (or whatever the standard plotting output is).

In particular, I'm using the Python API in a Jupyter notebook, and I want to use `FlowCal.excel_ui.process_beads_table()` and have its plots rendered in the notebook, but that doesn't work in the current build. Current build fails if you specify `plot_dir=None`, which implicitly requires that you save your plots to a directory if you want to see them (default behavior if you don't specify `plot_dir` is to dump the plot files in the current directory).

In contrast, `FlowCal.mef.get_transform_fxn()` exhibits the desired behavior (if `plot==True` and `plot_dir is None`, plot without saving to file). I tested this, and indeed the plots generated by `FlowCal.mef.get_transform_fxn()` are successfully rendered to a Jupyter notebook if you specify `plot=True` and `plot_dir=None'.
* minor note: `FlowCal.mef.get_transform_fxn()` only accepts `plot_dir=None` (not `plot_dir=False`), so maybe `FlowCal.excel_ui.process_beads_table()` and `FlowCal.excel_ui.process_samples_table` should only accept `plot_dir=None` to be consistent.

**Comment by castillohair** [comment]
Solution merged into branch develop.
