### ISSUE TITLE
Linear gain (`amplifier_gain`) is incorrectly extracted from our FCS files

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#219]
The `amplifier_gain` `FCSData` attribute is extracted from the `$PnG` keyword-value pair from the TEXT segment. It appears that FCS files from our current cytometer setup don't use that keyword-value pair to store the linear gain. Furthermore, it appears that the linear gain is stored in a proprietary keyword-value pair with the keyword `CytekP0nG`. (or maybe `CytekPnnG`? I assume a cytometer with more than 9 channels would populate keyword-value pairs with 2 nonzero digits in place of the `n`).

This means that any FCS files with linear gains other than 1.0 would be incorrectly processed to a.u. by `FlowCal.transform.to_rfi()` (a use case which admittedly doesn't happen much for me).

**Comment by castillohair** [comment]
Solution merged into branch develop.
