### ISSUE TITLE
Add kwargs catch-all to Excel UI process_beads_table() which gets passed to mef.get_transform_fxn()

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#222]
I'm using the Excel UI via the Python API to process bead files, and it's excluding some bead peaks that I don't want excluded in the subpopulation selection step. To get around this, I wanted to turn off the automated subpopulation selection step and just manually specify which peaks to keep and which peaks to exclude by placing `None` in the comma-separated list of MEF values on the Beads tab in the XLSX sheet. To achieve this, though, I had to copy the entire `excel_ui.process_beads_table()` function source code into my context (Jupyter notebook), update module names to match my namespace, and then add in 1 line to set `mef.get_transform_fxn(...,selection_fxn=None)`.

I think a better solution would be to add a `kwargs` catch-all parameter to `excel_ui.process_beads_table()` which would be passed to the internal `mef.get_transform_fxn()` call. This offers up the much simpler and generally much more flexible solution to my problem stated above:

```python
beads_samples, mef_transform_fxns, mef_outputs = excel_ui.process_beads_table(
    beads_table,
    instruments_table,
    get_transform_fxn_kwargs={'selection_fxn':None}    # <---
    base_dir=input_dir,
    verbose=verbose,
    plot=plot,
    plot_dir='plot_beads',
    full_output=True)
```

**Comment by castillohair** [comment]
Merged into branch develop.
