### ISSUE TITLE
FCSData fails to import FCS file when $PnV keyword is 'NA'

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#227]
I obtained an FCS file from an Attune NxT cytometer, and `FlowCal.io.FCSData()` failed to import it successfully (via FlowCal version 1.1.0), stating:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\FlowCal\io.py", line 1526, in __new__

ValueError: could not convert string to float: NA
```
The source of this error seems to be the fact that this FCS file stores a value of `'NA'` for the `$PnV` keyword for the `Time` channel. Queried via the `FlowCal.io.FCSFile` object:
```python
>>> fcs_file.text['$P1N']
'Time'
>>> fcs_file.text['$P1V']
'NA'
```
The relevant code for the `FCSData` object which underlies this error is here ([`FlowCal.io` module](https://github.com/taborlab/FlowCal/blob/ca52afae6594313dbcd82ce99bf4ca757cb0ea69/FlowCal/io.py#L1523)):
```python
# Detector voltage: Stored in the keyword parameter $PnV for channel n.
# The CellQuest Pro software saves the detector voltage in keyword
# parameters BD$WORD13, BD$WORD14, BD$WORD15... for channels 1, 2,
# 3...
if 'CREATOR' in fcs_file.text and \
        'CellQuest Pro' in fcs_file.text.get('CREATOR'):
    detector_voltage = [fcs_file.text.get('BD$WORD{}'.format(12 + i))
                        for i in range(1, num_channels + 1)]
else:
    detector_voltage = [fcs_file.text.get('$P{}V'.format(i))
                    for i in range(1, num_channels + 1)]
detector_voltage = [float(dvi) if dvi is not None else None
                    for dvi in detector_voltage]
detector_voltage = tuple(detector_voltage)
```
where the problem arises from a call to `float('NA')`, which throws the error originally reported above.

**Comment by JS3xton** [comment]
I can envision at least 3 different possible solutions:
1. specifically catching when detector voltage is `'NA'`:
    ```python
    if detector_voltage == 'NA':
        detector_voltage = np.nan
    ```
    or
    ```python
    detector_voltage = np.nan if detector_voltage == 'NA' else detector_voltage
    ```
2. trying to cast the detector voltage as a float and replacing with `np.nan` if it fails:
    ```python
    try:
        detector_voltage = float(detector_voltage)
    except:
        detector_voltage = np.nan
    ```
3.  trying to cast the detector voltage as a float and doing *nothing* (keep the original value) if it fails:
    ```python
    try:
        detector_voltage = float(detector_voltage)
    except:
        pass
    ```

**Comment by castillohair** [comment]
`d.get(key)` returns `None` if dictionary `d` does not contain `key`. The code currently assigns `None` to any keyword parameter that is not available in the `.fcs` file. I would favor keeping the behavior consistent with this.

So the solution might look something like the following:

```python
try:
    detector_voltage = float(detector_voltage)
except:
    detector_voltage = None
```

There might be a more elegant way to do this and preserve the original form, which is based on a list comprehension.

**Comment by JS3xton** [comment]
Do you think this qualifies as "keyword parameter that is not available"? That's what I've been going back and forth on. Because in fact there *is* a keyword parameter available (in contrast to when the keyword parameter is omitted entirely from the TEXT segment), and the acquisition software decided to populate it with `NA`.

My first two solutions were attempting to simply replace the string with a more python-appropriate interpretation (`np.nan`) and not crash the `FCSData` constructor, but you raise a good point that we already have an expected behavior (`None`) when a parameter is not available. If we opt to replace the original keyword parameter value, I agree with you that `None` is more consistent than `np.nan` for the general case of *any* failed call to `float()`. Favoring a hands-off solution, though, I'm actually leaning towards the 3rd solution I presented (try to make it a `float`, but pass it along to the user unmodified if that fails). `FCSData` should no longer fail upon construction, but it might present the user with unexpected `detector_voltage` values. I'm on the fence, though.

**Comment by castillohair** [comment]
"NA" clearly means that the information is not available. So in this particular case, it would be appropriate to set `detector_voltage` to `None`.

For the general case, however, I can see why you would want to blindly pass the string value `detector_voltage` if it fails to decode a float value. Against this, I would say that the FCS3.1 standard clearly constrains the `$PnV` parameter to be floating-point only. I have not found similar hard restrictions on the FCS2.0 and 3.0 standards (they're way less descriptive about each individual parameter), but the fact that this parameter is described as "detector voltage" and exemplified with a number since version 2.0 is enough to me to put all non-floats in the same bag of "not specified".

Another argument is that a lot of code in FlowCal assumes that `detector_voltage` is either a number or `None`, which is guaranteed in the current implementation. I haven't tested it, but I would bet that some code is going to break if we add another datatype. Modifying (and reviewing) code to handle this appropriately only to support a borderline non-standard case seems like too much effort to me.

**Comment by JS3xton** [comment]
> "NA" clearly means that the information is not available. So in this particular case, it would be appropriate to set `detector_voltage` to `None`.

In this case, I'd say "NA" is more like "not *applicable*" ("not available" sounds like we're missing information, which I don't think is the case here). This is just semantics, though. I agree that `None` seems appropriate here. Sounds like we favor:
```python
try:
    detector_voltage = float(detector_voltage)
except:
    detector_voltage = None
```
I'm less concerned about preserving the list comprehension; I favor code readability. You may also want to check out #220 if you have strong feelings on low level implementation details. Ideally, the solutions to this and #220 (which currently does *not* preserve the list comprehension on `amplifier_gain`) should be consistent with each other.

**Comment by castillohair** [comment]
I don't care too much about the comprehension.

If we're using `try-except`, it would be nice to catch the proper `ValueError` only.
