### ISSUE TITLE
No module named "excel_ui"

### ISSUE THREAD

**Issue by Mwehrs** [taborlab/FlowCal#256]
HI!
I installed FlowCal following the directions on the website but I get the following error once I try to run it:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-e1d3b74cbe6a> in <module>()
----> 1 import FlowCal

/Users/mwehrs/anaconda/lib/python3.5/site-packages/FlowCal-1.1.3-py3.5.egg/FlowCal/__init__.py in <module>()
     10 
     11 import io
---> 12 import excel_ui
     13 import gate
     14 import transform

ImportError: No module named 'excel_ui'
It seems to be installed tho. 

mwehrs-mr:FlowCal-master mwehrs$ python setup.py install
running install
running bdist_egg
running egg_info
writing top-level names to FlowCal.egg-info/top_level.txt
writing requirements to FlowCal.egg-info/requires.txt
writing dependency_links to FlowCal.egg-info/dependency_links.txt
writing FlowCal.egg-info/PKG-INFO
reading manifest file 'FlowCal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'FlowCal.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.6-x86_64/egg
creating build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/__init__.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/excel_ui.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/gate.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/io.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/mef.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/plot.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/stats.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
copying build/lib/FlowCal/transform.py -> build/bdist.macosx-10.6-x86_64/egg/FlowCal
byte-compiling build/bdist.macosx-10.6-x86_64/egg/FlowCal/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/FlowCal/excel_ui.py to excel_ui.cpython-35.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/FlowCal/gate.py to gate.cpython-35.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/FlowCal/io.py to io.cpython-35.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/FlowCal/mef.py to mef.cpython-35.pyc
  File "build/bdist.macosx-10.6-x86_64/egg/FlowCal/mef.py", line 22
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.6-x86_64/egg/FlowCal/plot.py to plot.cpython-35.pyc
  File "build/bdist.macosx-10.6-x86_64/egg/FlowCal/plot.py", line 62
    except ImportError, e:
                      ^
SyntaxError: invalid syntax

Any idea on how to fix it?

**Comment by JS3xton** [comment]
Hmmmm. My initial guess is that you are using Python 3 instead of Python 2. Can you check that you are using Python 2.7?

**Comment by Mwehrs** [comment]
Hi !
yes I am using python3. Is there a way to make it compatible with python3?
Thanks
Maren

**Comment by JS3xton** [comment]
### Python 3
`FlowCal` is currently built on top of Python 2.7. There has been talk of supporting Python 3 (see #100), but I don't think that will happen any time soon.

There may be tools available online that can port Python 2.7 code to Python 3 code that you could try, but I can't vouch for any of them.

### Virtual Environments
If you're using Anaconda, as recommended in the [`FlowCal` documentation](http://taborlab.github.io/FlowCal/getting_started/install_anaconda.html), but you need Python 3 for other applications, I would recommend that you take advantage of [Anaconda's virtual environments](https://conda.io/docs/using/envs.html) to install Python 2.7 alongside Python 3 and run `FlowCal` out of the Python 2.7 environment.

Specifically, I use the Anaconda command prompt to install and run `FlowCal`:

![image](https://cloud.githubusercontent.com/assets/2179825/26605262/fa4aa198-4552-11e7-9c92-067dfa29ea78.png)

On my Windows machine, in an Anaconda command prompt, I do the following:
```shell
# list current Anaconda virtual environments
> conda info -e

# create new Anaconda virtual environment for FlowCal version 1.1.3
> conda create -n FlowCalv1.1.3 python=2.7 anaconda
```
The `-n FlowCalv1.1.3` names the virtual environment, `python=2.7` instructs the Anaconda environment manager to set up a new environment on top of Python 2.7, and `anaconda` instructs the Anaconda environment manager to install all of the default packages that come with Anaconda in the new virtual environment (which includes widely used packages like `numpy`, `matplotlib`, and `pandas`).

Once the new Anaconda virtual environment has been created (which can take a few minutes), I [download the most recent release of FlowCal](https://github.com/taborlab/FlowCal/releases), I unzip the downloaded file and navigate my Anaconda command prompt to the unzipped `FlowCal/` folder (which should contain a `setup.py` file), I activate the new Anaconda virtual environment, and I manually perform the commands from the `Install FlowCal (Windows).bat` / `Install FlowCal (OSX)` scripts:

```shell
# activate new Anaconda virtual environment
> activate FlowCalv1.1.3

# install packages upon which FlowCal depends
(FlowCalv1.1.3) > python -m pip install -r requirements.txt --no-cache-dir

# install FlowCal
(FlowCalv1.1.3) > python setup.py install
```

If the install proceeds without errors, I can now use `FlowCal` from an Anaconda command prompt via either the native Python interpretor:

```python
> activate FlowCalv1.1.3

(FlowCalv1.1.3) > python

>>> import FlowCal
```

or via the `FlowCal` Excel UI:

```shell
> activate FlowCalv1.1.3

(FlowCalv1.1.3) > python -m FlowCal.excel_ui -v -p -H
```

**Comment by Mwehrs** [comment]
Thank you so much!
I think I got it to work now =)

**Comment by JS3xton** [comment]
Great! I'm gonna go ahead and close this issue then. Feel free to open it back up, though, if you have any other installation issues.
