### ISSUE TITLE
FCSData objects are not pickled correctly

### ISSUE THREAD

**Issue by SynbioLucas** [taborlab/FlowCal#277]
## Problem
FCSData objects appear to be incompatible with Python's built-in serialization module, [Pickle](https://docs.python.org/2/library/pickle.html). After serializing and then de-serializing an FCSData instance, the `channels` attribute becomes inaccessible. This may extend to other attributes as well. The `channels` attribute is critical because it is used for slicing and is required to be accessible for FlowCal's built-in plotting methods.

Fixing this issue is important because serialization eliminates the need to go through the extremely slow data extraction procedure each time plots are made.

### Before serialization: works fine
```python
import os, cPickle
import FlowCal as fc

base_dir = os.path.abspath(os.path.join(os.path.abspath('__file__'), '..', '..', 'Flow Data', '20170613'))
fn = os.path.join(base_dir, 'Data001.fcs')

test_fcs = fc.io.FCSData(fn)
print test_fcs.channels
```
#### Output
    ('TIME', 'FSC', 'SSC', 'FL1', 'FL2', 'FL3', 'SSCW', 'SSCA')

### Serialize, deserialize: broken
```python
test_file = os.path.join(os.path.abspath('C:\Users\Lucas\Desktop'), 'test_fcs.p')

with open(test_file, 'w') as outfile:
    cPickle.dump(test_fcs, outfile) # serialization

with open(test_file, 'r') as infile:
    test_fcs = cPickle.load(infile) # de-serialization

print test_fcs.channels
```
#### Output
    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-9-34e7fbe9bdc5> in <module>()
    ----> 1 test_fcs.channels
    

    C:\Users\Lucas\Anaconda2\lib\site-packages\FlowCal\io.pyc in channels(self)
       1067 
       1068         """
    -> 1069         return self._channels
       1070 
       1071     def amplification_type(self, channels=None):
    

    AttributeError: 'FCSData' object has no attribute '_channels'

## Notes
- This bug occurs when using both the standard `pickle` module and its C variant, `cPickle`.
- The file read/write mode does not affect this bug (i.e. `'w'` vs `'wb'`).

## Version numbers
- Python: `2.7.13 |Anaconda 4.0.0 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]` [from `sys.version`]
- FlowCal: 1.1.3

**Comment by castillohair** [comment]
A quick google search led me to this super relevant example: https://stackoverflow.com/questions/26598109/preserve-custom-attributes-when-pickling-subclass-of-numpy-array. I'm posting this for future reference. I'm not gonna be able to work on this for the time being, but you're free to propose a solution.
