### ISSUE TITLE
Logicle does not work on matplotlib before 2.0.0

### ISSUE THREAD

**Issue by castillohair** [taborlab/FlowCal#296]
This came up as part of full testing with minimum requirements.

During #263, I changed the logicle tick formatter from `LogFormatterMathtext` to `LogFormatterSciNotation` (see https://github.com/taborlab/FlowCal/pull/263/files#diff-054cea49ce36dff621b079c865e654bbL613). Turns out `LogFormatterSciNotation` does not exist in matplotlib before 2.0.0.

Rather than reverting to `LogFormatterMathtext` or figuring out how to achieve the desired behavior without `LogFormatterSciNotation`, I propose to change matplotlib's minimum requirements to 2.0.0.

**Comment by JS3xton** [comment]
Hmmm. Can you just copy the [`LogFormatterSciNotation` implementation](https://matplotlib.org/_modules/matplotlib/ticker.html#LogFormatterSciNotation) into `FlowCal`? It looks like it just requires inheriting from `LogFormatterMathtext`, which appears to exist back to at least `mpl 1.3.0`. If that doesn't work, though, then I don't really have anything against bumping up the minimum requirement to 2.0.0. It's just kinda nice to support as far back as we conveniently can.

**Comment by castillohair** [comment]
There are several reasons for why not to inherit from `LogFormatterMathText` to salvage backwards compatibility:

- Although `LogFormatterMathText` exists since matplotlib [v1.3.0](https://github.com/matplotlib/matplotlib/blob/v1.3.0/lib/matplotlib/ticker.py#L725), the code has changed with respect to the current last version [v2.2.2](https://github.com/matplotlib/matplotlib/blob/v2.2.2/lib/matplotlib/ticker.py#L1061). This means that copying and pasting code for `LogFormatterSciNotation` that inherits from `LogFormatterMathText` might not work in older versions anyway.
- There's a bad precedent with inheriting plotting classes in FlowCal. Up to [v1.1.1](https://github.com/taborlab/FlowCal/blob/v1.1.1/FlowCal/plot.py#L383), our custom `LogicleLocator` inherited from matplotlib's `SymmetricalLogLocator`. This was changed in [v1.1.2](https://github.com/taborlab/FlowCal/blob/v1.1.2/FlowCal/plot.py#L383), in response to issue #233 caused by matplotlib 2.0.0 changing `SymmetricalLogLocator` in a way that broke our `LogicleLocator`.
- Hardcoding `LogFormatterSciNotation` would make us miss any updates that matplotlib incorporates to its implementation.
