### ISSUE TITLE
askopenfilename() file selection box hangs after file selection in MacOS 10.13.6

### ISSUE THREAD

**Issue by felixekn** [taborlab/FlowCal#299]
After selecting an excel file through the file selection window generated by askopenfilename(), the window does not close until all flow files and the excel spreadsheet have been produced by excel_ui.py.

This is likely because tkinter in OSX waits till all processes are run in the main program thread before finishing its execution ([basis of hypothesis](https://stackoverflow.com/questions/16400533/why-ttk-progressbar-appears-after-process-in-tkinter)). 

By calling Tk().update() after askopenfilename(), the file selection box can be forced closed but this leaves a main tkinter window open which cannot be closed with Tk().withdraw() or Tk().iconify().

A proposed solution is to execute the tkinter GUI on a thread that is different from the main python execution thread (link to [threading](https://docs.python.org/2/library/threading.html?highlight=thread#threading.Thread)).

This file selection hang event was encountered in FlowCal 1.1.4 and 1.2.0 while running Anaconda2 5.1 (FlowCal 1.1.4) and Anaconda2 5.2 (FlowCal 1.2.0) in MacOS 10.13.6 (High Sierra).

**Comment by castillohair** [comment]
For the record, this didn't happen with your previous version of macOS, which was 10.12 Sierra, right?

**Comment by TimLafferty** [comment]
Oh good God. Somebody fix this.
