### ISSUE TITLE
modifying data of the s object.

### ISSUE THREAD

**Issue by aromanillos** [taborlab/FlowCal#319]
Hello, I have a question about loading data FlowCal.io.FCSData. I load a file using :

 s = FlowCal.io.FCSData(datafile)

and afterwards i would like to modify the units of one of the channels, from miliseconds to minutes basically. Assuming s is an array i try to do such as:

s[:,'HDR-T']=s[:,'HDR-T']/(60*1000)

however, after this operation s seems to be empty. Is this the way that is supposed to modified the data? or is not possible to do it?

kind regards

**Comment by aromanillos** [comment]
It seems the data is correctly modified, but when it tries to do: 

       FlowCal.plot.density2d(s, channels=['HDR-T', 'SSC-A'], mode='scatter',
        xscale ='linear', yscale='linear')

the scatter does not show the appropriate data. instead I had to find where the HDR-T was found in the plot, and apparently all the values are the same in the x-axis... could be a bug because the maginuted of y and x axes are different? the histogram2d is not well implemented then?

![errorflowcal](https://user-images.githubusercontent.com/54850514/69970524-afbfb480-151e-11ea-92e5-d0f780de4553.png)

**Comment by castillohair** [comment]
Hi,
Could you tell us what FlowCal version you're using? Would it be possible for you to send us the fcs file that you're having this issue with? That would help us a lot in trying to understand the problem.
Thanks.
