### ISSUE TITLE
Calibration with lab using CS&T beads

### ISSUE THREAD

**Issue by JJSong0805** [taborlab/FlowCal#322]
Hi, thanks for writing such awesome package which we've been using heavily on our project.

It's probably not an issue directly related to the code. However, we got stuck when trying to use the package for calibration of fcs data of different labs. Therefore we really want to hear the opinion from you to help us move forward.

The issue is we have two labs using different kinds of beads for daily QC which are RCP-30-5A and BD CS&T beads. The one using RCP beads has all the things we need for calibration with FlowCal such as daily beads.fcs, MESF of different channels. However the one using CS&T beads doesn't save their bead.fcs because the way they do for QC is to adjust the voltage of instrument to meet the target value of bright, mid and dim beads in arbitrary unit. The only clue we have for CS&T beads is the target value of bright, mid and dim beads which seem to be fixed. We were thinking about finding the correlation between the MESF value of RCP beads and target value of CS&T beads so that we could try fitting one to the other. However, we have regressions between MESF values and channel numbers of RCP beads but we only have target values of CS&T beads which makes it difficult to find the correlation between the two values.

We wonder if you have any insight for such task, for example, how to get the channel numbers of according dim, mid and bright target values of CS&T beads.

**Comment by JS3xton** [comment]
Hmm, interesting question. I've heard of self-calibrating instruments, but I don't have experience with them. Could you tease out the relationship between the fluorescence spaces by running beads on opposing cytometers? In particular, the RCP-30-5A beads on the calibrated CS&T instrument, but seeing the CS&T beads on the other instrument would also be interesting. Ultimately, this might result in a workflow where you perform self-calibration on the CS&T instrument but measure and use RCP-30-5A beads for calibration.

**Comment by JJSong0805** [comment]
Hi @JS3xton ,
Thanks for the quick reply! The way you proposed is quite ideal for us. However, we can only process the fcs data from the backend for now since we only have data provided by labs but we don't have access to the instruments. I may want to try re-scale the MESF value calibrated by RCP-30-5A beads back to (0, 262143) which is the common range of arbitrary unit, and see if that makes the data comparable to the self-calibrated one. To do this I need to get the parameters of the MESF regression line so that I can get the maximum MESF value of each channel (i.e., to_mef(262143)). However, I couldn't find the way to get the parameters in the document. Can you help point it out? 
And if you have any opinion toward this method please share it with us. Thanks!

**Comment by JS3xton** [comment]
Ahh, yeah if you don't have access to the instruments that makes it harder.

If you're using the Excel UI, the beads fluorescence model equation, parameters, and fit values can be found in the Beads tab of the [output excel file](https://flowcal.readthedocs.io/en/latest/excel_ui/outputs.html#output-excel-file).

If you're using the Python API, you'll have to dig those things out of the `fitting` dictionary returned by [`mef.get_transform_fxn`](https://flowcal.readthedocs.io/en/latest/reference/FlowCal.mef.html#FlowCal.mef.get_transform_fxn). If you're using the higher level [`excel_ui.process_beads_table`](https://flowcal.readthedocs.io/en/latest/reference/FlowCal.excel_ui.html#FlowCal.excel_ui.process_beads_table), the `fitting` dictionaries are packaged with other information into `MEFOutput` classes and returned as a list (called `mef_outputs` in the documentation). That list contains one `MEFOutput` for each entry in the beads table.
