### ISSUE TITLE
Bi-exponential scaling/trasformation

### ISSUE THREAD

**Issue by sinnamone** [taborlab/FlowCal#338]
Hi,

I'm wondering if there is a possibility in the transformation step to apply the bi-exponential transformation (scaling) like in Flow-jo.

Thanks in advance

**Comment by castillohair** [comment]
Hi,

We have no immediate plans to implement this, but feel free to submit a pull request if you're interested.

**Comment by JS3xton** [comment]
Hi @sinnamone,

To follow up, it's my understanding that FlowJo's bi-exponential (`Biex`) transformation [is a look-up table approximation of the Logicle transformation](https://docs.flowjo.com/flowjo/graphs-and-gating/gw-transform-overview/), which uses a linear scale near 0 and a logarithmic scale away from 0, and FlowCal _does_ support the Logicle transformation. So FlowCal may not be able to reproduce FlowJo's `Biex` transformation exactly, but it should be able to get pretty close.

If you're using [FlowCal's ExcelUI](https://flowcal.readthedocs.io/en/latest/excel_ui/index.html), the default visualization scale is `'logicle'`, so you should already see plots with Logicle scaling.

If you're visualizing data using the Python API, the functions in the [`FlowCal.plot`](https://flowcal.readthedocs.io/en/latest/reference/FlowCal.plot.html) module similarly default to `'logicle'` scaling. You can also specify this explicitly via the `xscale` and `yscale` parameters.

If you're using the Python API and want to apply a Logicle transformation to data, I suspect you should be able to do that using the [`FlowCal.transform.transform()`](https://flowcal.readthedocs.io/en/latest/reference/FlowCal.transform.html#FlowCal.transform.transform) function and the [`FlowCal.plot._LogicleTransform`](https://github.com/taborlab/FlowCal/blob/5e187b0975499cc7887a537df81c511b0ee4798a/FlowCal/plot.py#L220) class (see the [`matplotlib.transforms` documentation for how that works](https://matplotlib.org/api/transformations.html). I think you'd want the `transform_non_affine()` function?). You may have to tweak the Logicle scale parameters (`T`, `M`, and `W`) to get it to behave like FlowJo, though.

**Comment by sinnamone** [comment]
Hi @JS3xton,

thank you for the suggestion I will try to test logical transformation.

@castillohair  Thank you, this kind of transformation could be very usefully. 

Simone
