### ISSUE TITLE
Is there a way to export the .fcs data after beads calibration?

### ISSUE THREAD

**Issue by ppreshant** [taborlab/FlowCal#354]
I am using FlowCal in Python to load, transform and calibrate a bunch of .fcs files, but I would like to use a different program such as R/[ggcyto](https://github.com/RGLab/ggcyto) for visualization and gating. Or maybe even a GUI like FlowJo

It would be really convenient if I could save the calibrated .fcs data from FlowCal and use it somewhere else, is there an easy way to do this?

**Comment by JS3xton** [comment]
Hey, Prashant. If you're using the Python API, I recommend using `pandas` to save your `FCSData` objects as CSV or Excel files, which works pretty well on my end:

```python
import FlowCal as fc
import pandas as pd

fcs_data = fc.io.FCSData("input_file.fcs")

# transform or calibrate fcs_data

pd.DataFrame(data=fcs_data, columns=fcs_data.channels).to_csv("output_file.csv", index=None)
pd.DataFrame(data=fcs_data, columns=fcs_data.channels).to_excel("output_file.xlsx", index=None)
```

You can specify an index (i.e., the event number) if you want, and you can save space by exporting only a few channels of interest. XLSX files also appear to save a little space compared to uncompressed CSV files. You will lose the TEXT segment metadata using this approach, but you can also export the `fcs_data.text` dictionary to a CSV or JSON file if you still need that. If you don't want to use `pandas`, you can do something similar with [`numpy.savetxt()`](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html). (The `FCSData` object inherits from and behaves like a `numpy` array.)

The Excel UI does not save the transformed event lists back to disk as that would effectively duplicate the FCS files and consume a lot of additional space.

**Comment by ppreshant** [comment]
Thank you for the detailed suggestions John! I will try this and import the data into R.

Along with saving the data in tabular format, I was hoping that saving it as .fcs so that it can be processed as a regular .fcs file for which `R/ggcyto` has nice prebuilt visualizations, and can be opened even with GUI software like FlowJo. I discovered this package [fcswrite](https://github.com/ZELLMECHANIK-DRESDEN/fcswrite) so I'll also try massaging the FCSData's `ndarray` into that format and see if exporting might work. I'll post an update here

**Comment by JS3xton** [comment]
Ahh, yeah, if you need to repackage an `FCSData` object back into an FCS file to use it with other applications expecting FCS files, that's trickier, and `FlowCal` definitely doesn't support that right now. (You'd need to write inverse functions for the `FlowCal.io.read_fcs_header_segment()`, `FlowCal.io.read_fcs_text_segment()`, and `FlowCal.io.read_fcs_data_segment()` functions. Hopefully you'd be able to skip some of the tedious edge cases, though.) I've not used `fcswrite`, but it looks like a good thing to try.

**Comment by ppreshant** [comment]
Update: [fcswrite](https://github.com/ZELLMECHANIK-DRESDEN/fcswrite) package does the job! And I successfully tested reading back the .fcs file into FlowCal and also R's [flowWorkspace/load_cytoframe_from_fcs](https://rdrr.io/bioc/flowWorkspace/man/load_cytoframe_from_fcs.html)

Here's my script if you want to incorporate it into `FlowCal.io`

```py
def write_FCSdata_to_fcs(filepath, fcs_data,
                         channels='all'):
    """ save data to .fcs files with correct metadata 
    
    Parameters
    ----------
    filepath : str
        give the path of the final .fcs file to be saved, include the .fcs extension.
    channels : str
        'all' will save all channels;
        Future feature: A list of channels to be saved; only these will be subset from the file.
    fcs_data : FlowCal.io.FCSData
        FCSData file to be saved
        is a numpy ndarray (N data x D channel dimensions) with metadata and other features.

    Returns
    -------
    None. Just saves the file and prints the filename
    
    Corrects the $TOT metadata to the fix number of cells from the file
    Creates directory if it does not exist 

    """
    
    from fcswrite import write_fcs # import the fcswriting function
    
    # Create a directory if it does not exist
    # from https://stackoverflow.com/a/273227/9049673
    from pathlib import Path
    Path(filepath).parents[0].mkdir(parents=True, exist_ok=True)
    # Path object. get parent directory. make new directory, include parents
    
    
    # select channels
    if channels == 'all': channels = list(fcs_data.channels)
    # unsupported : saving only desired channels
    # text metadata needs to be updated to select and renumber PnX
    # PnX ; X = B,D,E,N,R,S ; n = 1,2,3, in order of channels
    # Use write_fcs(.. , data=fcs_data[:, channels])
    
    # Save data to file
    write_fcs(filename= filepath, 
              chn_names=channels, 
              data=fcs_data,
              # text_kw_pr=fcs_data.text, # causes duplicates in HEADER and TEXT
              compat_chn_names=False) # don't remove special chars
    
    # print success message
    print('\n', 'file saved : ', Path(filepath).name)
```

**Comment by castillohair** [comment]
Good to keep in mind if we ever decide to implement this, but for the time being I'm closing this.
