### ISSUE TITLE
Storing bead fit parameters

### ISSUE THREAD

**Issue by thoreusc** [taborlab/FlowCal#38]
We should be storing the results of the bead analysis. It would be best to put them back into the appropriate row in the 'bead' sheet.

This would make batch analysis of beads much easier (e.g. to look at bead data acquired at different gains, or to analyze bead data with different gate fractions).

**Comment by JS3xton** [comment]
Would also be nice if the fit model parameters were published to the standard curve image (eg. `std_crv_FL1_B1.png`) generated in the `plot_beads/` folder.

**Comment by castillohair** [comment]
Bead parameters are written to the Excel output file as for a2bb82e56eafce9217246627feafd188a664e636.

**Comment by castillohair** [comment]
This is an example of the output right now. Parameters are printed as a comma-separated list of values.

![image](https://cloud.githubusercontent.com/assets/1529481/13716008/fffa5f84-e79d-11e5-90fe-cdfa726193ef.png)

**Comment by castillohair** [comment]
Solved as part of #194.
