### ISSUE TITLE
Unpack FCSFile.data to DataFrame

### ISSUE THREAD

**Issue by JS3xton** [taborlab/FlowCal#91]
Unpacking an `FCSFile.data` numpy array into a pandas DataFrame seems useful, regardless of the final form of the `FCSData` object. A simple utility function in the `io` module to support this would be nice. I'm thinking of something along the lines of:

``` python
def fcs_data_to_df(fcs_file):
    '''Unpack data from DATA and TEXT segments of FCS file into pandas DataFrame.

    fcs_file    - FCSFile object

    returns     - pandas DataFrame
    '''
    df = pd.DataFrame(fcs_file.data)
    df.index.name = 'Event'

    # Label columns with channel names from TEXT segment
    df.columns = [fcs_file.text['$P{}N'.format(p)]
                  for p in xrange(1,int(fcs_file.text['$PAR'])+1)]
    return df
```

It should ideally support all known FCS file formats (BD or otherwise).

**Comment by castillohair** [comment]
Closing because we're satisfied with the current form of FCSData.
